import {SelectorValuesOptions} from "../types/filter.ts";
import {MovieLengthEnum} from "../enums/movieLength.ts";

export const languagesMovies: SelectorValuesOptions[] = [
    { id: "en", name: "Inglês" },
    { id: "es", name: "Espanhol" },
    { id: "fr", name: "Francês" },
    { id: "zh", name: "Chinês" },
    { id: "hi", name: "Hindi"},
    { id: "ja", name: "Japonês" },
    { id: "ko", name: "Coreano" },
    { id: "de", name: "Alemão" },
    { id: "it", name: "Italiano" },
    { id: "pt", name: "Português" },
    { id: "ru", name: "Russo" },
    { id: "ar", name: "Árabe" },
    { id: "tr", name: "Turco" },
    { id: "th", name: "Tailandês" },
    { id: "sv", name: "Sueco" },
    { id: "pl", name: "Polonês" },
    { id: "nl", name: "Holandês" },
    { id: "da", name: "Dinamarquês" },
    { id: "no", name: "Norueguês" },
    { id: "fi", name: "Finlandês" },
    { id: "cs", name: "Tcheco" },
    { id: "el", name: "Grego" },
    { id: "he", name: "Hebraico" },
    { id: "vi", name: "Vietnamita" },
    { id: "ta", name: "Tâmil" },
    { id: "te", name: "Telugu" },
    { id: "bn", name: "Bengali" },
    { id: "ml", name: "Malaiala" },
    { id: "uk", name: "Ucraniano" },
];

export const orderingMovies: SelectorValuesOptions[] = [
    { id: "title.desc", name: "Título"},
    { id: "popularity.desc", name: "Popularidade" },
    { id: "primary_release_date.desc", name: "Ano de lançamento" },
    { id: "vote_count.desc", name: "Mais votado" }
];

export const classificationMovies: SelectorValuesOptions[] = [
    { id: "", name:"Todos" },
    { id: "L", name: "Livre" },
    { id: "10", name: "12 anos" },
    { id: "12", name: "16 anos" },
    { id: "14", name: "12 anos" },
    { id: "16", name: "16 anos" },
    { id: "18", name: "18 anos" }
];

export const popularityMovies: SelectorValuesOptions[] = [
    { id: "80", name: "Alta (80+)" },
    { id: "79", name: "Baixa (menos de 80)" },
]

export const lengthMovieMovies: SelectorValuesOptions[] = [
    { id: Number(MovieLengthEnum.todos), name: 'Todos' },
    { id: Number(MovieLengthEnum.curta), name: 'Curta (menos de 60 minutos)' },
    { id: Number(MovieLengthEnum.media), name: 'Média (60-120 minutos)' },
    { id: Number(MovieLengthEnum.longa), name: 'Longa (mais de 120 minutos)' },
]

export const ratingMovies: SelectorValuesOptions[] = [
    { id: 1, name: "1"},
    { id: 2, name: "2"},
    { id: 3, name: "3"},
    { id: 4, name: "4"},
    { id: 5, name: "5"},
    { id: 6, name: "6"},
    { id: 7, name: "7"},
    { id: 8, name: "8"},
    { id: 9, name: "9"},
    { id: 10, name: "10"},
]

export const streamingMovies: SelectorValuesOptions[] = [
    { id: "8", name: "Netflix" },
    { id: "9", name: "Amazon Prime Video" },
    { id: "337", name: "Disney Plus" },
    { id: "15", name: "Hulu" },
    { id: "384", name: "HBO Max" },
    { id: "531", name: "Paramount+" },
    { id: "283", name: "Crunchyroll" },
    { id: "39", name: "NOW TV" },
    { id: "386", name: "Apple TV Plus" },
    { id: "350", name: "Apple iTunes" },
    { id: "307", name: "Claro Video" },
    { id: "167", name: "Sky Go" },
    { id: "29", name: "Google Play Movies" },
    { id: "3", name: "Google Play" },
    { id: "2", name: "Apple TV" },
    { id: "192", name: "YouTube" },
    { id: "7", name: "Vudu" },
    { id: "11", name: "Mubi" },
    { id: "68", name: "Microsoft Store" },
    { id: "179", name: "Telecine Play" },
    { id: "63", name: "Filmin" },
    { id: "190", name: "CuriosityStream" },
    { id: "96", name: "Canal+" },
    { id: "497", name: "Starz Play" },
    { id: "540", name: "Amazon Video" },
    { id: "100", name: "DirectTV" },
    { id: "521", name: "Globo Play" },
    { id: "546", name: "Rakuten TV" },
    { id: "551", name: "Movistar Play" },
    { id: "554", name: "Claro Video" },
    { id: "559", name: "Looke" },
    { id: "573", name: "Pluto TV" },
    { id: "579", name: "HBO Go" },
    { id: "580", name: "HBO Now" },
    { id: "581", name: "HBO" },
    { id: "582", name: "Peacock" },
    { id: "583", name: "Paramount+" },
    { id: "584", name: "Discovery+" },
    { id: "585", name: "AMC+" },
    { id: "586", name: "Showtime" },
    { id: "587", name: "Starz" },
    { id: "588", name: "BET+" },
    { id: "589", name: "Acorn TV" },
    { id: "590", name: "BritBox" },
    { id: "591", name: "Criterion Channel" },
    { id: "592", name: "Fandor" },
    { id: "593", name: "Hallmark Movies Now" },
    { id: "594", name: "History Vault" },
    { id: "595", name: "IMDb TV" },
    { id: "596", name: "Lifetime Movie Club" },
    { id: "597", name: "Pantaya" },
    { id: "598", name: "Shudder" },
    { id: "599", name: "Sundance Now" },
    { id: "600", name: "TCM" },
    { id: "601", name: "Topic" },
    { id: "602", name: "UP Faith & Family" },
    { id: "603", name: "Viki" },
    { id: "604", name: "WWE Network" },
    { id: "605", name: "Youtube Premium" },
    { id: "606", name: "Zee5" },
    { id: "607", name: "DocuBay" },
    { id: "608", name: "Hoichoi" },
    { id: "609", name: "Sun Nxt" },
    { id: "610", name: "Aha" },
    { id: "611", name: "Discovery+" },
    { id: "612", name: "Hotstar" },
    { id: "613", name: "SonyLIV" },
    { id: "614", name: "Voot" },
    { id: "615", name: "ZeePlex" },
    { id: "616", name: "Eros Now" },
    { id: "617", name: "MX Player" },
    { id: "618", name: "Tata Sky" },
    { id: "619", name: "Star+" },
    { id: "620", name: "Lionsgate Play" },
    { id: "621", name: "Blim" },
    { id: "622", name: "Filmzie" },
    { id: "623", name: "Plex" },
    { id: "624", name: "Popcornflix" },
]